name: Go Build and Release

on:
  # push:
  #   tags:
  #     - "v*"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1" # Adjust this to your Go version

      - name: Build with Make
        run: make build

      - name: Run tests
        run: make test

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          platforms=("linux" "macos" "windows")
          for platform in "${platforms[@]}"; do
            if [ -d "build/$platform" ]; then
              for binary in build/$platform/*; do
                asset_name=$(basename "$binary")
                echo "Uploading $asset_name"
                curl -H "Authorization: token $GITHUB_TOKEN" \
                     -H "Content-Type: application/octet-stream" \
                     --data-binary @"$binary" \
                     "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=${asset_name}"
              done
            else
              echo "Directory build/$platform does not exist, skipping..."
            fi
          done
